#!/bin/sh
#
# This script is a wrapper around presenterm, which primarily serves to autogenerate the tables of content.

set -eu
SCRIPT_DIR="$(realpath "$(dirname -- "$0")")"; readonly SCRIPT_DIR;
print() { printf "%b%b" "${1-""}" "${2-"\\n"}"; }
stderr() { print "$@" 1>&2; }
reportError() { stderr "$2"; return "$1"; }
verbosePrint() { { test -n "${VERBOSE_MODE+x}" && stderr "$@"; } || true; }

commandv() { command -v "$1" || reportError "$?" "Executable '$1' not found"; }


getNonOptionArgument() {
	while [ "$#" -gt 0 ]; do
		case "$1" in
			-*): ;;
			*)
				print "$1"
				break
				;;
		esac
		shift
	done
}




FILE="$(getNonOptionArgument "$@")"

if ! [ -f "$FILE" ]; then
	test -d "$FILE" && reportError 1 "'$FILE' is a directory, but wanted a file!"
	reportError 1 "File '$FILE' not found!"
fi


TOC_OUTPUT_FILE="toc.md"

awk '/^===+$/ && length(header) != 0 {print "- " header} {header=$0}' "$FILE" > "$TOC_OUTPUT_FILE"


exec presenterm "$@"
