#!/bin/sh
DELAY="0.5"

P_0_0="$(tmux display -p '#{pane_id}')"
P_0_1="$(tmux split -hP)"
P_0_2="$(tmux split -P)"

(
tmux resizep -t "$P_0_1" -D 1
tmux clock -t "$P_0_2"

sleep "$DELAY"
tmux send -t "$P_0_0" './hello-tux' enter


tmux send -t "$P_0_1" './hello-cow' enter

P_1_0="$(tmux new-window -Pd)"

sleep "$DELAY"
sleep "$DELAY"
tmux send -t "$P_1_0" "figlet -ct Hello World | lolcat" enter

sleep "$DELAY"
tmux send -t "$P_1_0" "cowsay tmux is truly awsome | lolcat" enter

P_2_0="$(tmux new-window -Pd)"
) &
